---
functional:
  - Пользователь должен иметь возможность играть против другого человека или бота.
  - Победителем должен являться тот, кто верно решил задачу и затратил на это меньше времени.
  - Игрок должен иметь возможность видеть в реальном времени редактор кода, свой и своего оппонента.
  - Игрок должен иметь возможность видеть в реальном времени вывод тестов, свой и своего оппонента.
  - Оба игрока должны иметь возможность менять язык программирования во время решения задачи.
  - Пользователь должен иметь возможность пригласить друга к игре по ссылке.
  - Пользователь должен иметь возможность выбирать сложность игры до ее начала.
  - Пользователь должен иметь возможность менять язык описания задачи.
  - Пользователь должен иметь возможность наблюдать за ходом игры других пользователей.
  - Пользователь должен иметь возможность регистрироваться в приложении.
  - Пользователь должен иметь возможность авторизоваться в приложении.
  - Зарегистрированным пользователям должна быть доступна возможность общаться в текстовом чате во время игры.
  - Пользователю должны быть доступны в записи его завершенные игры.
  - Пользователь должен иметь возможность завершить начатую игру.
  - В приложении должен быть реализован рейтинг пользователей за неделю, за месяц и за все время.
  - Интерфейс в записи завершенной игры не должен быть кликабельным.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Запись игры реализована в виде видео-проигрывателя.
implicit:
  - Чтобы определить победителя, нужно реализовать счетчик времени.
  - Чтобы пользователь видел редактор оппонента в реальном времени, необходимо реализовать оба редактора на одной странице.
  - Зарегестрированным пользователям необходимо предоставить выбор с кем играть, с ботом или человеком.
  - Необходимо реализовать возможность выбора игры для наблюдения за ней.
